// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrL-HET03FtqTJDUc7NwqWGcTUTSBGgyo',
    appId: '1:592306107503:android:2566d3bc9d90dce640899a',
    messagingSenderId: '592306107503',
    projectId: 'apnagodam-user',
    storageBucket: 'apnagodam-user.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPbbXxjzPGpEBpL2-IDuoheL_yoE3RHNA',
    appId: '1:592306107503:ios:e76a869cb1d2b9f940899a',
    messagingSenderId: '592306107503',
    projectId: 'apnagodam-user',
    storageBucket: 'apnagodam-user.firebasestorage.app',
    androidClientId: '592306107503-mru4kcvju46hd2lcu3d986633gbrejuq.apps.googleusercontent.com',
    iosBundleId: 'com.apnagodam',
  );

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIGFi2vpdLSC835UIVCNVPeFnGPmyd_uU',
    appId: '1:592306107503:web:8a10732f5aa78ad340899a',
    messagingSenderId: '592306107503',
    projectId: 'apnagodam-user',
    authDomain: 'apnagodam-user.firebaseapp.com',
    storageBucket: 'apnagodam-user.firebasestorage.app',
    measurementId: 'G-9RL4HQDQXB',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPbbXxjzPGpEBpL2-IDuoheL_yoE3RHNA',
    appId: '1:592306107503:ios:dec1f7d37babc27c40899a',
    messagingSenderId: '592306107503',
    projectId: 'apnagodam-user',
    storageBucket: 'apnagodam-user.firebasestorage.app',
    androidClientId: '592306107503-mru4kcvju46hd2lcu3d986633gbrejuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.apnagodam',
  );

  static  FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIGFi2vpdLSC835UIVCNVPeFnGPmyd_uU',
    appId: '1:592306107503:web:690335db1333b32f40899a',
    messagingSenderId: '592306107503',
    projectId: 'apnagodam-user',
    authDomain: 'apnagodam-user.firebaseapp.com',
    storageBucket: 'apnagodam-user.firebasestorage.app',
    measurementId: 'G-24LW8Z8QD0',
  );

}