// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrL-HET03FtqTJDUc7NwqWGcTUTSBGgyo',
    appId: '1:592306107503:android:2566d3bc9d90dce640899a',
    messagingSenderId: '592306107503',
    projectId: 'apnagodam-user',
    storageBucket: 'apnagodam-user.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPbbXxjzPGpEBpL2-IDuoheL_yoE3RHNA',
    appId: '1:592306107503:ios:e76a869cb1d2b9f940899a',
    messagingSenderId: '592306107503',
    projectId: 'apnagodam-user',
    storageBucket: 'apnagodam-user.firebasestorage.app',
    androidClientId: '592306107503-mru4kcvju46hd2lcu3d986633gbrejuq.apps.googleusercontent.com',
    iosBundleId: 'com.apnagodam',
  );
}
